# Generated by Django 2.0.5 on 2018-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourcenpool', '0002_auto_20180520_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(default='DefaultEdge', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='plz',
            field=models.IntegerField(default=96049),
            preserve_default=False,
        ),
    ]
